name: FancyEggs
version: 1.6
main: de.lmcstudio.fancyeggs.FancyEggs
api-version: '26.1'
softdepend: [Vault, PlaceholderAPI]
authors: [LMCStudio]
commands:
  fancyeggs:
    aliases: [eggs, fe]
    permission: fancyeggs.use
permissions:
  fancyeggs.use:
    default: true
  fancyeggs.admin:
    default: op
